Fix termbox in labs
The labmon1001 got deprecated in T224585 and now termbox in labs fails
with:
Error: getaddrinfo ENOTFOUND labmon1001.eqiad.wmnet

Change-Id: Ib3dba30ef08fcbea3923f2063156f64e9d60acf0